spring:
  application:
    name: vli
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vli?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
mybatis:
  type-aliases-package: com.vli.mapper.*
server:
  port: 5524
  servlet:
    context-path: /vli
thymeleaf:
  cache: false
  prefix: classpath:templates/
  suffix: .html
  encoding: UTF-8
  content-type: text/html
  mode: HTML5

#查询QQ信息接口
slt:
  #接口1
  path-one: http://api.ccswust.org/qqxt/api.php
#日志
logging:
  config: classpath:log4j2.yml